name: Dev

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Clean
        run: yarn cache clean
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
